### ISSUE TITLE
Score logic

### ISSUE THREAD

**Issue by cinegemadar** [cinegemadar/testris#3]
The scoring logic is missing from the game. Expected behaviour:
- When head, torso, leg pieces correctly aligned (next to each-other in the same rotation i.e. left-to-right, right-to-left, upside-down, straight), THEN
- all 3 piece must be removed from the stored locked pieces.
- 1 point needed to be added to the score

**Comment by cinegemadar** [comment]
please make sure:
- bomb pieces are not so frequent (less frequent than leg, head, torso)
- no score for exploding pieces.

**Comment by gkisida** [comment]
I started to implement the logic to join+disappear neighboring pieces and fall down the pieces above those.
