### ISSUE TITLE
Visual effect when pieces are disappearing 

### ISSUE THREAD

**Issue by cinegemadar** [cinegemadar/testris#40]
In the current implementation pieces are disappearing from one frame to the other when joint correctly. A nice visual effect would be beneficial to increase the user experience.

**Comment by gkisida** [comment]
Some effects could be added like:
- when a body is joined - before disappearing - indicate the body to the user. For example blinking/shaking pieces.
- when a body disappears, there can be a blast like animation
- when the bomb explodes TBD

The animation could be proportional to the game speed (TBC).
