### ISSUE TITLE
Sound and music

### ISSUE THREAD

**Issue by cinegemadar** [cinegemadar/testris#7]
If you have the talent come up with a nice bcg music and sound effects.

**Comment by gkisida** [comment]
What if the speed of the music was proportional to the level of the game speed? It can be funny but not sure.

**Comment by cinegemadar** [comment]
> What if the speed of the music was proportional to the level of the game speed? It can be funny but not sure.

I like the idea! I'll give it a try. Also, right now the music is not looped; I couldn't yet figure out how to make it repeating.

**Comment by gkisida** [comment]
I made the music looped in https://github.com/cinegemadar/testris/pull/4

**Comment by gkisida** [comment]
would be nice to add sound for bomb / joining / grid compacting
